[package]
name = "ucph-nielsine-touying"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Jørgen Baun Høst <https://github.com/jorgenhost>"]
license = "MIT"
description = "Slide template built on Touying for the University of Copenhagen."
repository = "https://github.com/jorgenhost/ucph-nielsine-touying"
keywords = ["presentation", "pre", "slide", "slides", "lecture", "touying", "beamer", "ucph", "copenhagen", "university of copenhagen"]
categories = ["presentation"]
compiler = "0.13.1"
exclude = [
  ".github",
  "docs",
  "scripts",
  "tests",
  ".typstignore",
  "Justfile",
  "examples",
  "thumbnail-dark.svg",
  "thumbnail-light.svg",
]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "assets/thumbnail.png"